[examples] Fix a few examples.
This is ported from the GTK2 branch, so it is not enough for GTK3.

Note the additions of the `-linkall` flag. As far as I can see this is
necessary in order to avoid:

```
Fatal error: exception Failure("Gobject.unsafe_create : type GtkFrame is not yet defined")
```
etc...